spring:
  application:
    name: rydar
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/rydar_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # development only - drops tables after shutdown.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false

