spring:
  application:
    name: rydar
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]  # reads .env when present
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false

server:
  port: ${PORT:8080}
